version: '3'

services:
 
 mariadb:
  build: ./requirements/mariadb
  image: mariadb
  container_name: mariadb-c
  restart: always
  env_file: .env
  volumes:
      - mariadb_data:/var/lib/mysql
  networks:
      -  inception_network
 
 wordpress:
  depends_on:
      - mariadb
  build: ./requirements/wordpress
  image: wordpress
  container_name: wordpress-c
  restart: always
  env_file: .env
  volumes:
      - wp_data:/var/www/
  networks:
      - inception_network

 nginx:
  depends_on:
      - wordpress
  build: ./requirements/nginx
  image: nginx
  container_name: nginx-c
  restart: always
  ports:
      - "443:443"
  networks:
      -  inception_network
  volumes:
      - wp_data:/var/www/

volumes:
 wp_data:
     driver: local
     driver_opts:
         type: 'none'
         o: 'bind'
         device: '/home/jacher/data/wp-data'
      
 mariadb_data:
     driver: local
     driver_opts:
         type: 'none'
         o: 'bind'
         device: '/home/jacher/data/mariadb-data'
     
networks:
 inception_network:

