version: '3'

services:
 
 mariadb-service:
  build: ./requirements/mariadb
  image: my-mariadb-image
  container_name: mariadb
  restart: always
  env_file: .env
  volumes:
      - mariadb_data_bis:/var/lib/mysql
  networks:
      -  inception_network
 
 wordpress-service:
  depends_on:
      - mariadb-service
  build: ./requirements/wordpress
  image: my-wordpress-image
  container_name: wordpress
  restart: always
  env_file: .env
  volumes:
      - wp_data_bis:/var/www/
  networks:
      - inception_network

 nginx-service:
  depends_on:
      - wordpress-service
  build: ./requirements/nginx
  image: my-nginx-image
  container_name: nginx
  restart: always
  ports:
      - "443:443"
  networks:
      -  inception_network
  volumes:
      - wp_data_bis:/var/www/

volumes:
 wp_data_bis:
     driver: local
     driver_opts:
         type: 'none'
         o: 'bind'
         device: '/Users/jacher/data_bis/wp_data_bis'
      
 mariadb_data_bis:
     driver: local
     driver_opts:
         type: 'none'
         o: 'bind'
         device: '/Users/jacher/data_bis/mariadb_data_bis'
     
networks:
 inception_network:

