version: '3.1'

services:

 db:
  image: mariadb
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: example

 web:
  image: nginx
  volumes:
    - ./templates:/etc/nginx/templates
  ports:
    - 8082:80
  environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80

 wordpress:
  image: wordpress
  restart: always
  ports:
    - 8081:80
  environment:
     WORDPRESS_DB_HOST: db
     WORDPRESS_DB_USER: exampleuser
     WORDPRESS_DB_PASSWORD: examplepass
     WORDPRESS_DB_NAME: exampledb
  volumes:
    - wordpress:/var/www/html

 db:
  image: mysql:5.7
  restart: always
  environment:
    MYSQL_DATABASE: exampledb
    MYSQL_USER: exampleuser
    MYSQL_PASSWORD: examplepass
    MYSQL_RANDOM_ROOT_PASSWORD: '1'
  volumes:
    - db:/var/lib/mysql
  
 adminer:
  image: adminer
  restart: always
  ports:
    - 8080:8080

volumes:
  wordpress:
  db: 
      
  
 
  #environment:
  #    WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
  #    WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
  # WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
  #    WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}

    # environment:
    # MYSQL_DATABASE: ${MYSQL_DATABASE}
    # MYSQL_USER:  ${MYSQL_USER}
    # MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    #MYSQL_RANDOM_ROOT_PASSWORD: '1'
