version: '3'

services:
 
 mariadb-service:
  build: ./requirements/mariadb
  image: my-mariadb-image
  container_name: mariadb
  restart: always
  env_file: .env
  environment:
      - MYSQL_DATABASE=wordpress_database
  volumes:
      - mariadb_data:/var/lib/mysql
  networks:
      -  inception_network
 
 wordpress-service:
  depends_on:
      - mariadb-service
  build: ./requirements/wordpress
  image: my-wordpress-image
  container_name: wordpress
  restart: always
  env_file: .env
  environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress_database
  volumes:
      - wp_data:/var/www/
  networks:
      - inception_network

 nginx-service:
  depends_on:
      - wordpress-service
  build: ./requirements/nginx
  image: my-nginx-image
  container_name: nginx
  restart: always
  ports:
      - "443:443"
  networks:
      -  inception_network
  volumes:
      - wp_data:/var/www/

volumes:
 wp_data:
     driver: local
     driver_opts:
         type: 'none'
         o: 'bind'
         device: '/Users/jacher/data/wp_data'
 mariadb_data:
     driver: local
     driver_opts:
         type: 'none'
         o: 'bind'
         device: '/Users/jacher/data/mariadb_data'
     
networks:
 inception_network:

